plugins {
    id 'com.android.application'
}

android {
    namespace = 'com.reappzuku.securityprobe'
    compileSdk = 37

    defaultConfig {
        applicationId = 'com.reappzuku.securityprobe'
        minSdk = 28
        targetSdk = 37
        versionCode = 1
        versionName = '1.0'
    }
}
